services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./database/:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  springboot:
    build:
      context: ./springboot
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "1234:1234"
